# Generated by Django 6.0.3 on 2026-03-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='uploads/catalog')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='uploads/catalog')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatalog', to='catalog_and_subcatalog.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'СубКаталог',
                'verbose_name_plural': 'СубКаталог',
                'ordering': ('name',),
            },
        ),
    ]
