# Generated by Django 6.0.3 on 2026-03-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_and_subcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='image',
        ),
    ]
