# Generated by Django 6.0.3 on 2026-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_and_subcatalog', '0002_remove_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcatalog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
