# Generated by Django 6.0.3 on 2026-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_and_subcatalog', '0003_subcatalog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
