# Generated by Django 6.0.3 on 2026-03-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_and_subcatalog', '0004_alter_subcatalog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('size', models.TextField(verbose_name='Размеры')),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('subcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='catalog_and_subcatalog.subcatalog', verbose_name='Каталог продукции')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='production.production')),
            ],
        ),
    ]
