# Generated by Django 6.0.3 on 2026-03-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='size',
        ),
        migrations.AddField(
            model_name='production',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Диаметр продукции'),
        ),
        migrations.AddField(
            model_name='production',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Высота продукции'),
        ),
        migrations.AddField(
            model_name='production',
            name='image',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Изображение карточки продукции'),
        ),
        migrations.AddField(
            model_name='production',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Длина продукции'),
        ),
        migrations.AddField(
            model_name='production',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='production',
            name='unit',
            field=models.CharField(choices=[('mm', 'миллиметры'), ('sm', 'сантиметры'), ('m', 'метры')], default='sm', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='production',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ширина продукции'),
        ),
    ]
