# Generated by Django 6.0.3 on 2026-03-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_production_size_production_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='nominal',
            field=models.CharField(blank=True, choices=[('rub', 'Рубли'), ('kaz', 'Тенге'), ('usd', 'Доллар')], default='kaz', max_length=20, null=True, verbose_name='Номинал валюты'),
        ),
    ]
