# Generated by Django 6.0.3 on 2026-03-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца аренды'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала аренды'),
        ),
    ]
