# Generated by Django 6.0.3 on 2026-03-29 11:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_end_date_alter_card_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
