# Generated by Django 6.0.3 on 2026-03-30 07:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Введите корректный номер телефона'}, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
